const fs = require('fs');
const data = require('./unsplash_data.json');
const imgUrls = data.results.map(r => r.urls.raw.split('?')[0]);

const provinces = {
    'central': [['Temple of the Tooth', 'Sacred Buddhist temple in Kandy.'], ['Gregory Lake', 'Scenic reservoir in Nuwara Eliya.'], ['Royal Botanical Gardens', 'Orchid collection in Peradeniya.'], ['Ambuluwawa Tower', 'Spiral tower in Gampola.'], ['Knuckles Mountain Range', 'Rugged trekking terrain.'], ['Pinnawala Elephant Orphanage', 'Elephant sanctuary nearby.'], ['Horton Plains', 'High altitude plateau park.'], ['Worlds End', 'Sheer precipice in Horton Plains.'], ['Bahirawakanda Vihara', 'Giant Buddha statue overlooking Kandy.'], ['Hunas Falls', 'Beautiful waterfall in Matale district.'], ['Dambulla Cave Temple', 'Golden temple complex.'], ['Pidurangala Rock', 'Alternative hike near Sigiriya.'], ['Udawatta Kele', 'Sanctuary in the heart of Kandy.'], ['Victoria Dam', 'Highest dam in Sri Lanka.'], ['Maduru Oya Park', 'Wildlife and ancient ruins.'], ['Sembuwatta Lake', 'Man-made lake with misty hills.'], ['St. Clair\'s Falls', 'Little Niagara of Sri Lanka.'], ['Devon Falls', 'Waterfall named after English coffee planter.'], ['Aluvihare Rock Temple', 'Where Pali Canon was written.'], ['Matale Spice Gardens', 'Educational spice tours.']],
    'southern': [['Galle Fort', 'Portuguese historical fortifications.'], ['Mirissa Beach', 'Whale watching paradise.'], ['Yala National Park', 'Wildlife (leopards and elephants).'], ['Unawatuna Beach', 'Crescent beach and palm trees.'], ['Tangalle', 'Pristine beaches and luxury stays.'], ['Weligama Bay', 'Ideal for beginner surfing.'], ['Hiriketiya Beach', 'Hidden horseshoe surf bay.'], ['Dondra Head Lighthouse', 'Southernmost point of Sri Lanka.'], ['Hummanaya Blowhole', 'Natural seawater blowhole.'], ['Koggala Lake', 'Serene lake with small islands.'], ['Handunugoda Tea Estate', 'Virgin White Tea production.'], ['Kushtarajagala', 'Rock-cut statue of Avalokiteshvara.'], ['Star Fort Matara', 'Dutch fort built in star shape.'], ['Polhena Beach', 'Safe snorkeling and turtle sightings.'], ['Rekawa Beach', 'Famous for turtle nesting.'], ['Madu River Safari', 'Boat ride through mangroves.'], ['Ahungalla Beach', 'Golden sands and palm luxury.'], ['Bentota Beach', 'Major water sports hub.'], ['Kosgoda Turtle Hatchery', 'Sea turtle conservation center.'], ['Kanneliya Forest', 'Lowland rainforest biodiversity.']],
    'western': [['Lotus Tower', 'Tallest South Asian tower.'], ['Negombo Beach', 'Golden sands near airport.'], ['Independence Square', 'Grand monument in Colombo.'], ['Galle Face Green', 'Ocean-side urban park.'], ['Mount Lavinia', 'Colonial charm beach resort.'], ['National Museum', 'Historic artifacts and art.'], ['Viharamahadevi Park', 'Colombo\'s largest public park.'], ['Gangaramaya Temple', 'Modern eclectic Buddhist temple.'], ['Beira Lake', 'Urban lake with Seema Malaka temple.'], ['St. Anthony\'s Shrine', 'Famous Catholic pilgrimage site.'], ['Bellanwila Temple', 'Venerated ancient Buddhist site.'], ['Bolgoda Lake', 'Largest natural lake in Sri Lanka.'], ['Kelaniya Temple', 'Sanctified by Buddha\'s visit.'], ['Apey Gama', 'Replica of a traditional village.'], ['Waters Edge', 'Recreational park in Battaramulla.'], ['Diyatha Uyana', 'Lakeside park and food stalls.'], ['Beddagana Park', 'Nature walk and bird watching.'], ['Attidiya Sanctuary', 'Wetland bird habitat.'], ['Dutch Hospital', 'Oldest building in Fort area.'], ['Pettah Market', 'Modern shopping on water.']],
    'eastern': [['Arugam Bay', 'Surfing point break destination.'], ['Pigeon Island', 'Coral reef national park.'], ['Trincomalee Harbour', 'Natural deep-water harbour.'], ['Nilaveli Beach', 'White sands and turquoise waters.'], ['Batticaloa Lagoon', 'Home of the singing fish.'], ['Uppuveli Beach', 'Relaxed vibe and seafood stalls.'], ['Koneswaram Temple', 'Classical Hindu temple on Swami Rock.'], ['Marble Beach', 'Hidden gem with crystal waters.'], ['Kanniya Hot Springs', 'Ancient therapeutic hot wells.'], ['Pasikudah Bay', 'Shallow waters and luxury resorts.'], ['Kalkudah Beach', 'Pristine and secluded sands.'], ['Ampara Tank', 'Large reservoir and wildlife.'], ['Buddhangala Monastery', 'Ancient ruins in Ampara.'], ['Lahugala Kitulana', 'National park for elephants.'], ['Magul Maha Viharaya', 'Site of royal wedding ceremony.'], ['Okanda Devalaya', 'Coastal shrine for pilgrims.'], ['Kumana National Park', 'Bird sanctuary and leopards.'], ['Gal Oya National Park', 'Boat safaris and wild elephants.'], ['Senanayake Samudraya', 'Largest reservoir in Sri Lanka.'], ['Elephant Rock', 'Popular viewpoint in Arugam Bay.']],
    'north-central': [['Sigiriya Rock', 'Ancient fortress and palace.'], ['Polonnaruwa', 'Ruins of ancient kingdom.'], ['Anuradhapura', 'Ancient sacred city and stupas.'], ['Mihintale', 'Birthplace of Buddhism here.'], ['Ritigala', 'Ancient forest monastery range.'], ['Isurumuniya', 'Famous for stone carvings.'], ['Sri Maha Bodhi', 'World\'s oldest planted tree.'], ['Ruwanwelisaya', 'Colossal bubble-shaped stupa.'], ['Jetavanaramaya', 'Tallest brick structure of antiquity.'], ['Abhayagiri Dagoba', 'Massive monastery ruins.'], ['Minneriya National', 'The Great Elephant Gathering.'], ['Kaudulla Park', 'Another hub for wild elephants.'], ['Giritale Tank', 'Scenic reservoir and ruins.'], ['Lankathilaka', 'High-walled massive brick structure.'], ['Gal Viharaya', 'Exquisite rock-cut Buddha statues.'], ['Vatadage', 'Circular relic house in Polonnaruwa.'], ['Hatadage', 'Ancient relic shrine of Tooth.'], ['Rankot Vihara', 'Largest dagoba in Polonnaruwa.'], ['Tivanka House', 'Exquisite ancient frescoes.'], ['Parakrama Samudra', 'The Sea of Parakrama reservoir.']],
    'uva': [['Nine Arches Bridge', 'Iconic colonial railway bridge.'], ['Ella Rock', 'Hike with panoramic views.'], ['Little Adam\'s Peak', 'Ridge-line viewpoints hike.'], ['Dunhinda Falls', 'Beautiful high waterfall.'], ['Lipton\'s Seat', 'Breathtaking tea estate viewpoint.'], ['Ravana Falls', 'Associated with Ramayana legend.'], ['Adisham Bungalow', 'St. Benedictine monastery.'], ['Buduruwagala', 'Colossal rock-cut Buddha figures.'], ['Diyaluma Falls', 'Sri Lanka\'s second highest waterfall.'], ['Bambarakanda Falls', 'Highest waterfall in the country.'], ['Muthiyangana Vihara', 'Ancient temple in Badulla.'], ['Narangala Mount', 'Popular mountain for camping.'], ['Maligawila Buddha', 'Free-standing ancient stone statue.'], ['Yudaganawa Stupa', 'One of the largest in Uva.'], ['Bogoda Bridge', 'Oldest wooden bridge in the country.'], ['Demodara Loop', 'Unique railway engineering marvel.'], ['Haputale Town', 'Misty town with sheer cliffs.'], ['Idalgashinna', 'Scenic railway station in the clouds.'], ['Sorabora Wewa', 'Ancient irrigation masterpiece.'], ['Rawana Cave', 'Legendary hiding place of Seetha.']],
    'northern': [['Jaffna Fort', 'Limestone colonial fortification.'], ['Nallur Kovil', 'Grand Hindu temple complex.'], ['Nagadeepa Temple', 'Ancient island temple site.'], ['Casuarina Beach', 'Shallow blue karainagar beach.'], ['Delft Island', 'Wild horses and history.'], ['Point Pedro', 'Northernmost edge of Sri Lanka.'], ['Kandarodai Stupas', 'Enigmatic cluster of small stupas.'], ['Keerimalai Springs', 'Sacred coastal bathing ponds.'], ['Elephant Pass', 'Strategic gateway to Jaffna.'], ['Charty Beach', 'Secluded sandy beach in Jaffna.'], ['Mandaitivu Island', 'Scenic island linked by causeway.'], ['Karainagar Causeway', 'Beautiful drive through the sea.'], ['Vallipuram Temple', 'Ancient Vishnu temple site.'], ['Jaffna Library', 'Symbol of cultural resilience.'], ['Sangilean Arch', 'Archway of the last Jaffna king.'], ['Minister\'s Palace', 'Ruins of a royal residence.'], ['Naguleswaram', 'One of the five Ishwarams.'], ['Dambakola Patuna', 'Where Sangamitta landed here.'], ['Pooneryn Fort', 'Remote Dutch ruins in the north.'], ['Iranamadu Tank', 'Largest reservoir in northern region.']],
    'north-western': [['Kalpitiya Lagoon', 'Kite surfing and dolphins.'], ['Munneswaram', 'Ancient Chilaw Hindu complex.'], ['Wilpattu National', 'Sri Lanka\'s largest park.'], ['Panduwasnuwara', 'Ancient kingdom ruins site.'], ['Yapahuwa Rock', 'Historic capital rock stair.'], ['Muthurajawela', 'Important coastal wetland.'], ['Chilaw Beach', 'Stretching coastal sands.'], ['Marawila Beach', 'Quiet resort town atmosphere.'], ['Puttalam Lagoon', 'Vast lagoon with salt pans.'], ['Paramakanda Rock', 'Temple on a sheer rock cliff.'], ['Dambadeniya', 'Ancient capital with hill ruins.'], ['Ethagala Rock', 'The Elephant Rock viewpoint.'], ['Ridi Vihara', 'Ancient silver forest monastery.'], ['Athugala Statue', 'Giant Buddha on Kurunegala cliff.'], ['Talawila Church', 'Historic St. Anne\'s shrine.'], ['Kudiramalai Point', 'Ancient port with red sands.'], ['Arankele Hermitage', 'Ancient hermitage ruins.'], ['Nikaweratiya Tank', 'Beautiful inland reservoir.'], ['Kurunegala Lake', 'Heart of the rock city.'], ['Sandalankawa', 'Center of traditional agriculture.']],
    'sabaragamuwa': [['Adams Peak', 'Spiritual mountain pilgrimage.'], ['Ratnapura Gem Mines', 'Mining for sapphires and rubies.'], ['Udawalawe Park', 'Elephant herds in the wild.'], ['Elephant Orphanage', 'Pinnawala sanctuary.'], ['Belilena Caves', 'Prehistoric archaeological site.'], ['Saman Devalaya', 'Grand shrine of God Saman.'], ['Kitulgala Rafting', 'Adventure hub for river rafting.'], ['Sinharaja Forest', 'UNESCO rainforest biodiversity.'], ['Bopath Ella', 'Bo-leaf shaped waterfall.'], ['Dover Cave', 'Intriguing natural formations.'], ['Kirindi Ella', 'Cascading waterfall in Ratnapura.'], ['Batadombalena', 'Balangoda man habitat site.'], ['Wavulpane Cave', 'Cave of bats and fossils.'], ['Maduwanwela', 'Archaic aristocrat mansion.'], ['Sankapala Vihara', 'Ancient temple in a cave.'], ['Katugas Ella', 'Tucked away forest waterfall.'], ['Pelmadulla', 'Heart of the gem mining region.'], ['Godakawela', 'Gateway to the southern plains.'], ['Kolonne Valley', 'Scenic agricultural landscape.'], ['Bulutota Pass', 'Winding road with 10 hairpins.']]
};

const provinceCoords = {
    'central': [7.29, 80.63],
    'southern': [6.03, 80.21],
    'western': [6.92, 79.86],
    'eastern': [8.56, 81.23],
    'north-central': [8.31, 80.40],
    'uva': [6.99, 81.05],
    'northern': [9.66, 80.00],
    'north-western': [7.58, 79.83],
    'sabaragamuwa': [6.68, 80.40]
};

const finalPlaces = {};
let imgIndex = 0;

for (let prov in provinces) {
    const base = provinceCoords[prov];
    finalPlaces[prov] = provinces[prov].map((p, idx) => ({
        id: `${prov[0]}${idx + 1}`,
        name: p[0],
        desc: p[1],
        lat: base[0] + (Math.random() - 0.5) * 0.05,
        lon: base[1] + (Math.random() - 0.5) * 0.05,
        img: imgUrls[imgIndex++ % imgUrls.length]
    }));
}

fs.writeFileSync('expanded_places.json', JSON.stringify(finalPlaces, null, 2));
console.log('Expanded places JSON generated with TIGHTER coordinate anchors.');
